### ISSUE TITLE
Persistent query window

### ISSUE THREAD

**Issue by jesper-bengtson** [tmpbla/Kopitiam#105]
Feature request.

It would be fantastic if the query window saved its output between invocations, possibly with an option in the options menu to determine how much text should be saved.

Furthermore, it would also be great if the size of the query window was also maintained (and possibly made a bit larger by default).

**Comment by ale-f** [comment]
Commit 1780a74bfcbec6ca472303f6c83ef2c0d9765fef adds a cache, commit 670fd15755585a37027ca2862765073a15b429bb makes the query dialog's size (a bit) persistent, and commit 7113e6246f9f889f9a03e85bd3342293ce694623 increases its default size. Closing.
